# Generated by Django 4.2.4 on 2023-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='role',
            field=models.CharField(default='emp', max_length=5),
        ),
    ]
