# Generated by Django 4.2.4 on 2023-08-21 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userauthonticationmodel_datetime_employee_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthonticationmodel',
            name='datetime_employee_registered',
        ),
        migrations.RemoveField(
            model_name='userauthonticationmodel',
            name='special_token',
        ),
        migrations.AddField(
            model_name='userauthonticationmodel',
            name='datetime_user_registered',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 13, 6, 7, 730322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userauthonticationmodel',
            name='datetime_user_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 13, 6, 7, 730322, tzinfo=datetime.timezone.utc)),
        ),
    ]
