# Generated by Django 4.2.4 on 2023-08-22 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userauthonticationmodel_datetime_user_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='datetime_user_registered',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 15, 56, 54, 296374)),
        ),
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='datetime_user_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 15, 56, 54, 296374)),
        ),
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
