# Generated by Django 4.2.4 on 2023-08-23 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_employeelogindetails_datetime_employee_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogindetails',
            name='datetime_employee_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 27, 38, 83369)),
        ),
        migrations.AddField(
            model_name='employeelogindetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_details', to='users.userauthonticationmodel'),
        ),
        migrations.AlterField(
            model_name='employeelogindetails',
            name='datetime_employee_registered',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 27, 38, 83369)),
        ),
        migrations.AlterField(
            model_name='employeelogindetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='datetime_user_registered',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 27, 38, 82878)),
        ),
        migrations.AlterField(
            model_name='userauthonticationmodel',
            name='datetime_user_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 27, 38, 82878)),
        ),
    ]
